version: '3.1'

services:
    db:
      image: postgres:latest
      restart: always
      env_file:
        - .env
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
        
    server:
      build: .
      restart: always
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - .:/app
