name: CI/CD Pipeline

on:
  push:
    branches:
      - variant

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker-image:latest

  test:
    name: Run tests and linters
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - run: docker run docker-image:latest pytest

  deploy:
    name: Deploy to Server
    needs:
      - build
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker pull docker-image:latest
              docker run -d -p 80:80 docker-image:latest
