name: Development Compose CI

on:
  push:
    branches: [ "variant" ]
  pull_request:
    branches: [ "variant" ]

jobs:
  run:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: "Create env file"
      run:
        echo "POSTGRES_USER=postgres 
              POSTGRES_PASSWORD=postgres 
              POSTGRES_DB=postgres 
              POSTGRES_HOST=db 
              POSTGRES_PORT=5432 
              API_KEY=c4f80daf " > .env
    - name: Run server
      run: docker compose -f docker-compose.yml up --build -d --remove-orphans
permissions: 
  contents: write