name: CI/CD Pipeline

on:
  push:
    branches:
      - variant

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/docker-image:latest

  test:
    name: Run tests and linters
    needs:
      - build
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
            envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            envkey_API_KEY: ${{ secrets.API_KEY }}
            file_name: .env
            fail_on_empty: false

      - run: |
          docker-compose run --env-file .env --rm server pytest test_main.py shell

  deploy:
    name: Deploy to Server
    needs:
      - build
      - test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.HOST_SSH_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker pull ${{ secrets.DOCKERHUB_USER }}/docker-image:latest
              cd ~/CICD/ && git checkout variant
              git pull git@movie_api:${{ secrets.OWNER }}/movie_api_.git
              docker-compose up -d
              
